// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbvUSZJv9sqeEQseJ8G51AOQQ7_-zEgP0',
    appId: '1:649655952166:web:d70c85372b5a9e238dd7e7',
    messagingSenderId: '649655952166',
    projectId: 'pingme-a09b0',
    authDomain: 'pingme-a09b0.firebaseapp.com',
    storageBucket: 'pingme-a09b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSC_cjDArtUUDKl4jnkJ0sjqWQ9AF0IQk',
    appId: '1:649655952166:android:56d0a9550f10cd3a8dd7e7',
    messagingSenderId: '649655952166',
    projectId: 'pingme-a09b0',
    storageBucket: 'pingme-a09b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALSzWr7RHgl7kR0nHg9EsP66JcQ5UNAC0',
    appId: '1:649655952166:ios:00a6e434aad20e598dd7e7',
    messagingSenderId: '649655952166',
    projectId: 'pingme-a09b0',
    storageBucket: 'pingme-a09b0.firebasestorage.app',
    iosBundleId: 'com.example.pingme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALSzWr7RHgl7kR0nHg9EsP66JcQ5UNAC0',
    appId: '1:649655952166:ios:00a6e434aad20e598dd7e7',
    messagingSenderId: '649655952166',
    projectId: 'pingme-a09b0',
    storageBucket: 'pingme-a09b0.firebasestorage.app',
    iosBundleId: 'com.example.pingme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbvUSZJv9sqeEQseJ8G51AOQQ7_-zEgP0',
    appId: '1:649655952166:web:e178cf5a7b66b81a8dd7e7',
    messagingSenderId: '649655952166',
    projectId: 'pingme-a09b0',
    authDomain: 'pingme-a09b0.firebaseapp.com',
    storageBucket: 'pingme-a09b0.firebasestorage.app',
  );
}
